---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 719169492085972992-qhbuslD1AUUFJyGKkpuYnQObdxguWq1
:access_token_secret: SfGdsCcUwLLaR0fSUYCqQ9ZSXuyezYIOxsMkPH6V09SIL
